// to-do:
// - briefly discuss built-in non-terminals like Byte and AsciiCharS
// - the Non-Terminals, Synthesized Attributes, and Inherited Attributions section may need examples
// - maybe add a simple exercise or two?


= User Datagram Protocol

For our first exercise, we examine the https://en.wikipedia.org/wiki/User_Datagram_Protocol[User Datagram Protocol (UDP)].
The UDP specification can be found in https://tools.ietf.org/html/rfc768[IETF RFC 768].
UDP is a transport layer protocol used alongside IP.
UDP does not provide some valuable guarantees, such as reliable and in-order messaging. as is provided by TCP.
However, it is simple and has minimal overhead.
This makes it a great introductory example use case for Parsley!

== Declarations

A format specification in Parsley is constructed via a sequence of declarations, each declaration belonging to one of the following four groups:

- `use` declarations that specify other Parsley files whose declarations shall be included. These are similar to `include` in C or `import` in Python.
- `type` definitions that allow users to specify their own types.
- `fun` and `recfun` declarations that correspond to functions and recursive functions respectively.
- `format` block declarations that specify non-terminal definitions.

In this first lesson, we introduce `format` and `type` declarations.

== A (Very) Brief Introduction to Parsley Types

The specification states that the UDP header comprises four fields corresponding to the source port, destination port, length, and checksum.
Each is of two bytes, but in our specification, we treat the source port, destination port, and length fields as integers.
Following the UDP header is the payload or data.
Given this structure, we can declare a new `type` to capture a UDP packet:
....
type udp_packet = {
  source_port: int,
  destination_port: int,
  length: int,
  checksum: [byte],
  data: [byte]
}
....

This may look confusing. But let's go over it step by step.

=== Atomic Types

Parsley supports a variety of atomic or built-in types:

- `byte`: captures a byte
- `int`: captures an integer
- `double`: captures a floating-point
- `string`: captures a sequence of characters
- `bool`: captures a Boolean or truth valuable
- `endian`: captures endian values that express what byte ordering to use when interpreting integer values
- `unit`: a type to express that a function returns nothing (similar to void in C)

=== User-Defined Types

Parsley also supports user-defined types. We can construct these user-defined types via type declarations of the form:

....
type type_name = type_form
....

where `type_name and `type_form` correspond to the identifier for the type and the structure or form of the type.

Some examples of user-defined type declarations are:

- `type byte_list = [byte]` is a list of bytes
- `type int_bool_tuple = (int, bool)` is a tuple with element types `int` and `bool` respectively
- `type list_of_tuples = [(int, int)]` is a list of two tuples, each of which contain two integers. This may, for example, be used to express points in a two-dimensional plane.

A special kind of user-defined type is the record type.
The record type comprises a number of component type fields and has the general form of:

....
type type_name = {
  field_name_0: field_type_0,
  field_name_1: field_type_1,
  ...
  field_name_n: field_type_n
}
....

Each line within the curly brackets specifies a component field via a field name and type.
Following each field declaration, aside from the last one, we see a `,` that serves as a delimiter between field declarations.

NOTE: There is more to discuss about types, notably variant types and type variables. We will cover these topics in future lessons.

=== Declaring the UDP Packet Type

Let's return to our UDP packet.

....
type udp_packet = {
  source_port: int,
  destination_port: int,
  length: int,
  checksum: [byte],
  data: [byte]
}
....

The `udp_packet` is a record type that comprises five component subtypes or fields.

The first four fields correspond to the UDP header: `source_port` is an int, `destination_port` is an int, `length` is an int, and `checksum` is a list of bytes.
The last component field is the payload captured in `data`, which is again a list of bytes.
Now that we have captured the general structure of a UDP packet, we can move on to the specification.

== The Format Block

The `format` block is essential to _every_ Parsley specification.
This is where we define non-terminals and, as the name suggests, specify the format of the specification.
The `format` block has the general form (some details are missing but we'll get to them):

....
format {
  NT1 n1 ... := ...;;
  NT2 n2 ... := ...;;
  NTFIN nfin ... := ...
}
....

The `format` block is simply a sequence of non-terminal declarations.
Each declaration, except for the last, must end with `;;`, which serves as a non-terminal declaration delimiter.

=== Non-Terminals, Synthesized Attributes, and Inherited Attributes

Parsley provides a rich subgrammar that has some similarity with BNF but also a number of key differences.
Here, we will only cover the basics; more topics will be introduced in subsequent lessons.
A non-terminal is derived using one or more production rules that are separated by `;`, which is the ordered choice operator.
Each production rule is a sequence of rule elements.
A sequence of rule elements is matched if the input matches the rule elements.

In this first lesson, we cover the standard approach to declaring non-terminals.
A non-terminal in Parsley has a type associated with it, which is always the record type using the standard approach.
This type is specified by synthesized attributes, which can be thought of as attributes that are derived as we perform the matching.
Additionally, a type declaration may include inherited attributes, which are attributes that are provided at the beginning of the pattern matching process by the caller.

NOTE: Parsley also supports an alternative approach for declaring byte-vector--valued non-terminals, one which uses regular expressions. We shall cover this in a future lesson!

=== Working Through the UDP Packet Format

Now, let's work on developing a Parsley specification for a UDP packet:

....
format {
  UDPPacket udpp (e: endian) {u: udp_packet} := ...
}
....

We still have to fill in the details obviously, but this is a good start.
We have a non-terminal entitled UDPPacket that has the short name of udpp.
UDPPacket has the inherited attribute `e` of type `endian`, inherited attributes like these are specified within parentheses.
And it has the synthesized attribute `u` of type `udp_packet`, which we had defined earlier; synthesized attributes like these are specified within curly brackes.


Now, let's work on the rule elements.
Well, the UDP specification states the header comprises 2 bytes for the source port, 2 bytes for the destination port, 2 bytes (or a 16 bit integer) for the length, and 2 bytes for the checksum.
Thus, we create four variables to capture these parts of the header.
And, of course, we have the data whose length is derived from the length field.

....
format {
  UDPPacket udpp (e: endian) {u: udp_packet} :=
    source_port = UInt16<endian=e>
    destination_port = UInt16<endian=e>
    length = UInt16<endian=e>
    checksum = (Byte^2)
    data = (Byte^(length - 8)) // subtract 8 for the UDP header length
    [length >= 8] // length field must be at least 8, the UDP header length
}
....

The variables `source_port`, `destination_port`, and `length` are assigned 16-bit unsigned integer values of the endianness specified by the inherited attribute `e`.
The variable `checksum` is assigned a two bye value by applying the user-defined `Byte` type in conjunction with the bounded repeat operator (`^`).
A 16 bit unsigned integer of the endianness specified by the inherited attributed `e` is assigned to the length variable.
Last, we read the data.
We determine the amount of data bytes to read by subtracting 8 from the length field.
Then, we read in those bytes by again applying the bounded repeat operator on the `Byte` type.
We note that the ordering of these assignments matters and is done in accordance with the UDP specification.
The ordering of these rule elements tell us how any parsers generated from this Parsley specification should go about consuming the input.

=== Finishing Up

All that is left is to perform a simple check on the `length` field and assign values to the synthesized variables.
We will do this using constraints and action blocks.

....
format {
  UDPPacket udpp (e: endian) {u: udp_packet} :=
    source_port = UInt16<endian=e>
    destination_port = UInt16<endian=e>
    length = UInt16<endian=e>
    checksum = (Byte^2)
    data = (Byte^(length - 8))
    [length >= 8]
    {
      udpp.u.source_port := source_port;
      udpp.u.destination_port := destination_port;
      udpp.u.length := length;
      udpp.u.checksum := checksum;
      udpp.u.data := data
    }
}

....

=== Constraints

A constraint is simply a parsing check.
That is, a constraint captures a Boolean-valued expression that determines whether or not to continue with the current production rule.
If the expression evaluates to a false Boolean value, then the constraint is not met and the production rule does not apply.
If, however, the constraint evaluates to a true Boolean value, then the constraint is met and we move on to the next rule element in the production rule.

In our UDP example, the constraint `[length >= 8]` does a check to ensure the `length` variable is assigned a value of at least 8.
If it were smaller than 8, we can tell, right off the bat, that the packet is malformed as the header itself is 8 bytes.

=== Action Blocks

The assignment of values to the synthesized attributes is performed with the action block, which is delimited by `{` and `}`.
The `:=`  symbol in action blocks denote assignment.
Each assignment statement in an action block aside from the last must end with the `;` delimiter.
There are other uses for action blocks as well, which we will cover them in future lessons.

In our UDP example, `udpp` is the short name for the non-terminal we are working on.
`udpp.u` refers to the `udp_packet` record attached to the `udpp` non-terminal.
In a straightforward fashion, we are simply assigning the fields in the `udpp.u` record the values of the variables that we have obtained by reading the input earlier.

Thus, we have our final Parsley file:

....
// This Parsley file is based on the UDP specification: https://tools.ietf.org/html/rfc768

// We make no assumption about whether we are using IPv4 or IPv6.
// However, we also don't perform some of the requisite checks
// using length and checksum as they would require knowing what
// version of IP we are using.

type udp_packet = {
  source_port: int,
  destination_port: int,
  length: int,
  checksum: [byte],
  data: [byte]
}

format {
  UDPPacket udpp (e: endian) {u: udp_packet} :=
    source_port = UInt16<endian=e>
    destination_port = UInt16<endian=e>
    length = UInt16<endian=e>
    checksum = (Byte^2)
    data = (Byte^(length - 8)) // subtract 8 for the UDP header length
    [length >= 8] // length field must be at least 8, the UDP header length
    {
      udpp.u.source_port := source_port;
      udpp.u.destination_port := destination_port;
      udpp.u.length := length;
      udpp.u.checksum := checksum;
      udpp.u.data := data
    }
}
....

=== Comments

You may noticed that we have incorporated some comments in our final Parsley file.
Comments in Parsley begin with two forward slash characters (`//`).
Everything that follows the `//` delimiter until the following new line character is part of the comment.

===== Navigation: <<overview.adoc, &#8593; Overview>> | <<pbm.adoc, &#8594; Next Lesson>> | <<#need_to_link, &#128196; Documentation>>
