// to-do:
// - briefly discuss built-in non-terminals like Byte and AsciiCharS
// - the Non-Terminals, Synthesized Attributes, and Inherited Attributions section may need examples
// - maybe add a simple exercise or two?


= User Datagram Protocol

For our first exercise, we examine the https://en.wikipedia.org/wiki/User_Datagram_Protocol[User Datagram Protocol (UDP)].
The UDP specification can be found in https://tools.ietf.org/html/rfc768[IETF RFC 768].
UDP is a transport layer protocol used alongside IP.
In contrast to TCP, another transport layer protocol, UDP does not provide some valuable guarantees, such as reliability and in-order messaging.
However, UDP is lightweight and simple, making it a great introductory example use case for this Parsley tutorial.

== Declarations

A format specification in Parsley is constructed via a sequence of <<../intro.adoc#structure-of-a-parsley-specification-file, declarations>>.
Currently, there are four classes of declarations:

- `use` declarations that specify other Parsley files whose declarations shall be included. These are similar to `include` in C or `import` in Python.
- `type` definitions that allow users to specify their own types.
- `fun` and `recfun` declarations that correspond to functions and recursive functions respectively.
- `format` block declarations that specify non-terminal definitions.

In this first lesson, we introduce the `format` and `type` declarations.

== A (Very) Brief Introduction to Parsley Types

The specification states that the UDP header comprises four fields corresponding to the source port, destination port, length, and checksum.
Each is of two bytes, but in our specification, we treat the source port, destination port, and length fields as integers.
Following the UDP header is the payload or data.
Given this structure, we can declare a new `type` to capture a UDP packet:

....
type udp_packet = {
  source_port: int,
  destination_port: int,
  length: int,
  checksum: [byte],
  data: [byte]
}
....

We provide a quick primer on types here but a more comprehensive treatment can be found in the <<../expressions.adoc#types, documentation>>.

=== Atomic Types

Parsley supports a variety of atomic or built-in types:

- `byte`: captures a byte
- `int`: captures an integer
- `double`: captures a floating-point
- `string`: captures a sequence of characters
- `bool`: captures a Boolean or truth valuable
- `endian`: captures endian values that express what byte ordering to use when interpreting integer values
- `unit`: a type to express that a function returns nothing (similar to void in C)

=== User-Defined Types

Parsley also supports user-defined types. We can construct these user-defined types via type declarations of the form:

....
type type_name = type_form
....

where `type_name` and `type_form` correspond to the identifier for the type and the structure or form of the type.

Some examples of user-defined type declarations are:

- `type byte_list = [byte]` is a list of bytes
- `type int_bool_tuple = (int, bool)` is a tuple with element types `int` and `bool` respectively
- `type list_of_tuples = [(int, int)]` is a list of two-tuples, each of which contain two integers. This may, for example, be used to express points in a two-dimensional plane.

A special kind of user-defined type is the record type.
The record type comprises a number of component type fields and has the general form of:

....
type type_name = {
  field_name_0: field_type_0,
  field_name_1: field_type_1,
  ...
  field_name_n: field_type_n
}
....

Each line within the curly brackets specifies a component field via a field name and type.
Each field declaration, aside from the last one, is terminated by a `,` delimiter.

NOTE: There is much more to discuss about types, notably variant types and type variables. The Parsley <<../expressions.adoc#types, documentation on types>> discusses these topics further.

=== Declaring the UDP Packet Type

Let's return to our UDP packet.

....
type udp_packet = {
  source_port: int,
  destination_port: int,
  length: int,
  checksum: [byte],
  data: [byte]
}
....

The `udp_packet` is a record type that comprises five component subtypes or fields.

The first four fields correspond to the UDP header: `source_port` is an int, `destination_port` is an int, `length` is an int, and `checksum` is a list of bytes.
The last component field is the payload captured in `data`, which is again a list of bytes.
Now that we have captured the general structure of a UDP packet, we can move on to the specification.

== The Format Block

The `format` block is essential to _every_ Parsley specification.
This is where we define non-terminals and, as the name suggests, specify the format of the specification.
The `format` block has the general form:

....
format {
  NT1 n1 ... := ...;;
  NT2 n2 ... := ...;;
  ...
}
....

The `format` block is simply a sequence of non-terminal definitions.
Each definition, except for the last, must end with `;;`, which serves as a non-terminal definition delimiter.

=== Non-Terminals, Synthesized Attributes, and Inherited Attributes

Parsley provides a rich subgrammar that has some similarity with https://en.wikipedia.org/wiki/Backus–Naur_form[BNF] but also a number of key differences.
Here, we will only cover the basics; more topics will be introduced in subsequent lessons.
A <<../grammar.adoc#defining-non-terminals, non-terminal>> is derived using one or more production rules that are separated by `;`, the ordered choice operator.
Each production rule is a sequence of rule elements.
A sequence of rule elements is matched if the input matches each of the rule elements in order.

In this first lesson, we cover the standard approach to defining non-terminals.
A non-terminal in Parsley has a type associated with it, which is always the record type using the standard approach.
This type is specified by synthesized attributes, which can be thought of as attributes that are derived as we perform the matching.
Additionally, a type declaration may include inherited attributes, which are attributes that are provided when the non-terminal is used in a rule element or invoked by a call from external application code.


NOTE: Parsley also supports an alternative approach for defining byte-vector--valued non-terminals, one which uses regular expressions. We shall cover this in a future lesson!

=== Working Through the UDP Packet Format

Now, let's work on developing a Parsley specification for a UDP packet:

....
format {
  UDPPacket udpp {u: udp_packet} := ...
}
....

We still have to fill in the details obviously, but this is a good start.
We have a non-terminal entitled `UDPPacket` that has the short name of `udpp`.
And it has the synthesized attribute `u` of type `udp_packet`, which we had defined earlier; synthesized attributes like these are specified within curly brackets.

NOTE: While the original specification does not explicitly require using the big-endian byte order,
the https://tools.ietf.org/html/rfc1700[Assigned Numbers RFC] specifies that Internet Protocols should be expressed in network byte order, i.e., big-endian byte order.
Hence, we follow this approach. However, If we had instead wished to pass in an endian value as an inherited attribute to UDPPacket, we would have written: `UDPPacket udpp (e: endian) {u: udp_packet} := ...`.

Now, let's work on the rule elements.
The UDP specification states the header comprises 2 bytes for the source port, 2 bytes for the destination port, 2 bytes (or a 16 bit integer) for the length, and 2 bytes for the checksum.
Thus, we have four identifiers (`source_port`, `destination_port`, `length`, `checksum`) to capture these parts of the header.
And, of course, we have `data` whose length is derived from the value matched by the `length` identifier.

....
format {
  UDPPacket udpp {u: udp_packet} :=
    source_port = UInt16<endian=endian::Big()>
    destination_port = UInt16<endian=endian::Big()>
    length = UInt16<endian=endian::Big()>
    checksum = (Byte^2)
    [length >= 8] // length field must be at least 8, the UDP header length
    data = (Byte^(length - 8)) // subtract 8 for the UDP header length
}
....

`UInt16 (endian: endian)` and `Byte` are built-in non-terminals that match a 16-bit unsigned integer and a byte respectively.
The identifiers `source_port`, `destination_port`, and `length` are assigned 16-bit unsigned integer values of the endianness `endian::Big()`.
The identifier `checksum` is assigned a two byte value by applying the `Byte` type in conjunction with the bounded repeat operator (`^`) with an operand of 2, indicating that two bytes should be matched.
A 16-bit unsigned integer of the endianness `endian::Big()` is assigned to the length identifier.

NOTE: The <<../stdlib.adoc#, Parsley Library Standard Documentation>> provides an in-depth discussion of built-in variant types, built-in non-terminals, and module operations.

Last, we must read in the data, but this requires ensuring the length value is reasonable.
We do this by imposing a constraint.

==== Constraints

A constraint is simply a parsing check.
More precisely, a constraint captures a Boolean-valued expression that determines whether or not to continue with the current production rule.
If the expression evaluates to a false Boolean value, then the constraint is not met and the production rule does not apply.
If, however, the constraint evaluates to a true Boolean value, then the constraint is met and we move on to the next rule element in the production rule.

In our UDP example, the constraint `[length >= 8]` does a check to ensure the `length` variable is assigned a value of at least `8`.
If it were assigned a value less than `8`, then we can immediately determine that the packet is malformed since the header itself is 8 bytes.

Finally, we determine the amount of data bytes to read by subtracting 8 (the header length) from the value captured by the `length` identifier.
Then, we read in those bytes by, once again, applying the bounded repeat operator to the `Byte` non-terminal with an operand of `length - 8`.

==== Action Blocks

All that is left is to assign values to the synthesized variables.
We do this via action blocks:

....
format {
  UDPPacket udpp {u: udp_packet} :=
    ...
    {
      udpp.u.source_port := source_port;
      udpp.u.destination_port := destination_port;
      udpp.u.length := length;
      udpp.u.checksum := checksum;
      udpp.u.data := data
    }
}
....


The assignment of values to the synthesized attributes is performed by the action block, which is delimited by `{` and `}`.
The `:=`  symbol in action blocks denote assignment.
Each assignment statement in an action block aside from the last must end with the `;` delimiter.
There are other uses for action blocks as well, and we will cover them in future lessons.

In our UDP example, `udpp` is the short name for the non-terminal we are working on.
`udpp.u` refers to the `udp_packet` record attached to the `udpp` non-terminal.
In a straightforward fashion, we are simply assigning the fields in the `udpp.u` record the values of the variables that we have obtained by reading the input earlier.

==== The Final Parsley File

Thus, we have our final Parsley file (`udp.ply`):

....
type udp_packet = {
  source_port: int,
  destination_port: int,
  length: int,
  checksum: [byte],
  data: [byte]
}

format {
  UDPPacket udpp {u: udp_packet} :=
    source_port = UInt16<endian=endian::Big()>
    destination_port = UInt16<endian=endian::Big()>
    length = UInt16<endian=endian::Big()>
    checksum = (Byte^2)
    [length >= 8] // length field must be at least 8, the UDP header length
    data = (Byte^(length - 8)) // subtract 8 for the UDP header length
    {
      udpp.u.source_port := source_port;
      udpp.u.destination_port := destination_port;
      udpp.u.length := length;
      udpp.u.checksum := checksum;
      udpp.u.data := data
    }
}
....

==== Comments

You may noticed that we have incorporated some comments in our final Parsley file.
Comments in Parsley begin with two forward slash characters (`//`).
Everything that follows the `//` delimiter until the following new line character is part of the comment.

==== Do We Need a `udp_packet` Type?

We had earlier declared a `udp_packet` type, which is used as a synthesized attribute in the UDPPacket non-terminal declaration.
Of course, we did not _have to_ define such a type.
Indeed, we could have instead supplied synthesized attributes corresponding to the type's member fields.
We have provided such an implementation in `udp_alt.ply` and also pasted the contents of such a file below.

....
format {
  UDPPacket udpp {source_port: int, destination_port: int, length: int,
                  checksum: [byte], data: [byte]} :=
    source_port = UInt16<endian=endian::Big()>
    destination_port = UInt16<endian=endian::Big()>
    length = UInt16<endian=endian::Big()>
    checksum = (Byte^2)
    [length >= 8] // length field must be at least 8, the UDP header length
    data = (Byte^(length - 8)) // subtract 8 for the UDP header length
    {
      udpp.source_port := source_port;
      udpp.destination_port := destination_port;
      udpp.length := length;
      udpp.checksum := checksum;
      udpp.data := data
    }
}
....

That said, there are numerous benefits to declaring and using a record type, e.g., modularization, code brevity, readability, and consequently improved security.
These benefits are especially pronounced in larger projects that make heavy use of the user-defined type.
In the next lesson, we will demonstrate how to use the `udp_packet` type when implementing a subset of IPv4.


[red]#Navigation:# <<overview.adoc#, &#8593; Tutorial Overview>> | <<ipv4.adoc#, &#8594; Next Lesson>> | <<../readme.adoc#, &#128196; Documentation>>
